language: ruby

before_install:
- gem install bundler -v 1.12.5

cache: bundler

rvm:
  - 2.0.0

sudo: required

addons:
  apt:
    packages:
    - dnsutils

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email:
    on_success: never
